# Generated by Django 5.0 on 2023-12-12 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="medics",
        ),
    ]
