# Generated by Django 5.0 on 2024-02-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0007_recordmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="title",
            field=models.CharField(
                default="New Chat", max_length=128, verbose_name="title"
            ),
        ),
    ]
